version: "3.8"

volumes:
  auth-db-data:
  auth-api-data:

networks:
  auth-network:

services:

  auth_db:
    image: mysql:latest

    volumes:
      - auth-db-data:/var/lib/mysql

    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PORT: ${MYSQL_DATABASE_PORT}

    networks:
      - auth-network

    healthcheck:
       test: 'echo "select now(); " | mysql -h ${MYSQL_DATABASE_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD}'
       interval: 1s
       retries: 10
       start_period: 10s
       timeout: 1s

    ports:
    - "3306:3306"

  auth_api:
    build:
      context: .
      dockerfile: ./docker/FastAPI/Dockerfile

    volumes:
    - auth-api-data:/media
    - ./ssl:/app/ssl

    depends_on:
      db:
        condition: service_healthy

    env_file: .env
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

    working_dir: "/app"

    ports:
    - "8000:8000"

    command: >
      sh -c "python test_api.py &&
             uvicorn main:app --host 0.0.0.0 --ssl-keyfile /app/ssl/certificate.key --ssl-certfile /app/ssl/certificate.crt --workers 4"

    networks:
    - auth-network

  auth_web:
    build:
      context: .
      dockerfile: ./docker/Svelte/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - auth-network

  # nginx:
  #   image: nginx:latest

  #   restart: always

  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl

  #   ports:
  #     - "8080:80"
  #     - "8443:443"

  #   depends_on:
  #     - web

  #   networks:
  #   - my-network
